language: java

install:
  - mvn clean test -B -V

after_success:
  - mvn -DrepoToken=$COVERALLS_TOKEN coveralls:report

deploy:
  provider: script
  script: bash build-resources/travis-release.sh
  on:
    branch: master