language: java

# Extract the signing certificates if the encrypted environment variables are passed by travis.
before_install:
  - cd $TRAVIS_BUILD_DIR && bash build-resources/extract_jar_signing_artifacts.sh $encrypted_e586968263a2_key $encrypted_e586968263a2_iv

# The environment variable checks ensure that signed jars (built as part of release builds) are
# not built on pull requests, only mainline builds.
install:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] || mvn clean install -DskipTests=true -B -V'
  - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || mvn -P release clean install -DskipTests=true -B -V'

# This re-runs the maven lifecycle with tests for coverage reporting
script:
  - mvn test jacoco:report -B

after_success:
  - if [ "$COVERALLS_TOKEN" != "" ]; then cd $TRAVIS_BUILD_DIR/test-operations && mvn -P release -DrepoToken=$COVERALLS_TOKEN coveralls:report; fi

deploy:
  provider: script
  script: cd $TRAVIS_BUILD_DIR && bash build-resources/travis-release.sh
  on:
    branch: master
