language: java

before_install:
  - openssl aes-256-cbc -K $encrypted_e586968263a2_key -iv $encrypted_e586968263a2_iv -in build-resources/gpg_files.tar.enc -out gpg_files.tar -d

install:
  - mvn clean test -B -V

after_success:
  - mvn -DrepoToken=$COVERALLS_TOKEN coveralls:report

deploy:
  provider: script
  script: bash build-resources/travis-release.sh
  on:
    branch: master