language: java

before_install:
  - openssl aes-256-cbc -K $encrypted_e586968263a2_key -iv $encrypted_e586968263a2_iv -in build-resources/gpg_files.tar.enc -out gpg_files.tar -d
  - tar -f gpg_files.tar -xO gpg-secret-keys | $GPG_EXECUTABLE --import
  - tar -f gpg_files.tar -xO gpg-ownertrust | $GPG_EXECUTABLE --import-ownertrust

install:
  - mvn clean verify -B -V -P release

after_success:
  - cd $TRAVIS_BUILD_DIR/test-operations && mvn -DrepoToken=$COVERALLS_TOKEN coveralls:report -P release

deploy:
  provider: script
  script: bash build-resources/travis-release.sh
  on:
    branch: master
